-- Insert sample survey responses for testing (with correct constraints)
INSERT INTO survey_responses (
  website_design_rating,
  treatment_type,
  doctor_listening,
  explanation_clarity,
  consultation_time,
  nps_score,
  how_did_you_know_us,
  waiting_time,
  referral_details,
  appointment_type,
  communication_clarity,
  reception_friendliness,
  clinic_environment,
  body_area,
  other_treatment,
  additional_comments,
  other_body_area,
  created_at
) VALUES 
-- Batch 1 (30 responses)
(5, 'Toxina Botulínica', 5, 5, 4, 9, 'Recomendación', 'bueno', NULL, 'Presencial', 5, 5, 5, 'Rostro', NULL, 'Excelente atención, muy profesional', NULL, NOW() - INTERVAL '45 days'),
(4, 'Rellenos Dérmicos', 4, 4, 3, 8, 'Redes sociales', 'normal', NULL, 'Presencial', 4, 4, 4, 'Labios', NULL, 'Muy satisfecha con los resultados', NULL, NOW() - INTERVAL '44 days'),
(3, 'Peeling Químico', 4, 3, 3, 7, 'Google', 'normal', NULL, 'Presencial', 3, 4, 3, 'Rostro', NULL, 'Buen servicio en general', NULL, NOW() - INTERVAL '43 days'),
(5, 'Láser', 5, 5, 5, 10, 'Recomendación', 'bueno', 'Dr. González me recomendó', 'Presencial', 5, 5, 5, 'Piernas', NULL, 'Increíble experiencia, superó mis expectativas', NULL, NOW() - INTERVAL '42 days'),
(3, 'Mesoterapia', 3, 3, 2, 6, 'Publicidad', 'malo', NULL, 'Presencial', 3, 3, 3, 'Abdomen', NULL, 'El tratamiento fue efectivo pero la espera fue larga', NULL, NOW() - INTERVAL '41 days'),
(5, 'Radiofrecuencia', 5, 4, 4, 9, 'Recomendación', 'normal', NULL, 'Presencial', 4, 5, 5, 'Rostro', NULL, 'Excelente profesionalismo del equipo', NULL, NOW() - INTERVAL '40 days'),
(4, 'Toxina Botulínica', 4, 5, 3, 8, 'Redes sociales', 'bueno', NULL, 'Presencial', 5, 4, 4, 'Frente', NULL, 'Muy contenta con el resultado natural', NULL, NOW() - INTERVAL '39 days'),
(2, 'Otro', 3, 2, 2, 5, 'Google', 'malo', NULL, 'Presencial', 2, 3, 2, 'Otro', 'Crioterapia', 'La espera fue muy larga y el servicio regular', 'Espalda', NOW() - INTERVAL '38 days'),
(5, 'Rellenos Dérmicos', 5, 5, 5, 10, 'Recomendación', 'bueno', 'Mi hermana me recomendó', 'Presencial', 5, 5, 5, 'Pómulos', NULL, 'Perfecto! No puedo estar más feliz', NULL, NOW() - INTERVAL '37 days'),
(3, 'Peeling Químico', 4, 3, 3, 7, 'Redes sociales', 'normal', NULL, 'Presencial', 3, 4, 3, 'Rostro', NULL, 'Buenos resultados, recomendaría', NULL, NOW() - INTERVAL '36 days'),
(5, 'Láser', 5, 5, 4, 9, 'Google', 'normal', NULL, 'Presencial', 5, 5, 5, 'Axilas', NULL, 'Muy efectivo y rápido', NULL, NOW() - INTERVAL '35 days'),
(4, 'Mesoterapia', 4, 4, 3, 8, 'Recomendación', 'normal', NULL, 'Presencial', 4, 4, 4, 'Rostro', NULL, 'Buena experiencia general', NULL, NOW() - INTERVAL '34 days'),
(3, 'Radiofrecuencia', 3, 3, 3, 6, 'Publicidad', 'malo', NULL, 'Presencial', 3, 3, 3, 'Abdomen', NULL, 'Servicio aceptable pero mejorable', NULL, NOW() - INTERVAL '33 days'),
(5, 'Toxina Botulínica', 5, 5, 5, 10, 'Recomendación', 'bueno', 'Dr. Martínez', 'Presencial', 5, 5, 5, 'Rostro', NULL, 'Perfecta experiencia en todos los aspectos', NULL, NOW() - INTERVAL '32 days'),
(4, 'Rellenos Dérmicos', 5, 4, 3, 8, 'Redes sociales', 'normal', NULL, 'Presencial', 4, 5, 4, 'Labios', NULL, 'Muy natural el resultado', NULL, NOW() - INTERVAL '31 days'),
(3, 'Peeling Químico', 3, 3, 3, 7, 'Google', 'normal', NULL, 'Presencial', 3, 3, 3, 'Rostro', NULL, 'Satisfecha con el tratamiento', NULL, NOW() - INTERVAL '30 days'),
(5, 'Láser', 5, 5, 4, 9, 'Recomendación', 'bueno', NULL, 'Presencial', 5, 5, 5, 'Piernas', NULL, 'Excelente tecnología y atención', NULL, NOW() - INTERVAL '29 days'),
(2, 'Mesoterapia', 3, 2, 2, 5, 'Publicidad', 'malo', NULL, 'Presencial', 2, 3, 2, 'Glúteos', NULL, 'Demasiada espera, servicio regular', NULL, NOW() - INTERVAL '28 days'),
(4, 'Radiofrecuencia', 4, 4, 3, 8, 'Redes sociales', 'normal', NULL, 'Presencial', 4, 4, 4, 'Rostro', NULL, 'Buenos resultados y atención', NULL, NOW() - INTERVAL '27 days'),
(5, 'Toxina Botulínica', 5, 5, 5, 10, 'Recomendación', 'bueno', 'Amiga del trabajo', 'Presencial', 5, 5, 5, 'Entrecejo', NULL, 'Increíble profesionalismo y resultados', NULL, NOW() - INTERVAL '26 days'),
(3, 'Otro', 3, 3, 2, 6, 'Google', 'malo', NULL, 'Presencial', 3, 3, 3, 'Otro', 'Hidratación facial', 'Servicio correcto pero nada excepcional', 'Cuello', NOW() - INTERVAL '25 days'),
(5, 'Rellenos Dérmicos', 5, 5, 4, 9, 'Recomendación', 'normal', NULL, 'Presencial', 5, 5, 5, 'Pómulos', NULL, 'Fantástico resultado, muy profesional', NULL, NOW() - INTERVAL '24 days'),
(3, 'Peeling Químico', 4, 3, 3, 7, 'Redes sociales', 'normal', NULL, 'Presencial', 3, 4, 3, 'Rostro', NULL, 'Buen tratamiento y seguimiento', NULL, NOW() - INTERVAL '23 days'),
(4, 'Láser', 4, 4, 3, 8, 'Google', 'normal', NULL, 'Presencial', 4, 4, 4, 'Axilas', NULL, 'Muy efectivo, volveré', NULL, NOW() - INTERVAL '22 days'),
(5, 'Mesoterapia', 5, 5, 5, 10, 'Recomendación', 'bueno', 'Dermatóloga', 'Presencial', 5, 5, 5, 'Rostro', NULL, 'Excelente en todos los aspectos', NULL, NOW() - INTERVAL '21 days'),
(2, 'Radiofrecuencia', 2, 2, 1, 4, 'Publicidad', 'malo', NULL, 'Presencial', 2, 2, 2, 'Abdomen', NULL, 'Mucha espera y resultados no tan buenos', NULL, NOW() - INTERVAL '20 days'),
(5, 'Toxina Botulínica', 5, 5, 4, 9, 'Redes sociales', 'bueno', NULL, 'Presencial', 5, 5, 5, 'Rostro', NULL, 'Muy satisfecha, recomendaré', NULL, NOW() - INTERVAL '19 days'),
(4, 'Rellenos Dérmicos', 4, 4, 3, 8, 'Recomendación', 'normal', NULL, 'Presencial', 4, 4, 4, 'Labios', NULL, 'Resultado muy natural y bonito', NULL, NOW() - INTERVAL '18 days'),
(3, 'Peeling Químico', 3, 3, 3, 7, 'Google', 'normal', NULL, 'Presencial', 3, 3, 3, 'Rostro', NULL, 'Tratamiento efectivo', NULL, NOW() - INTERVAL '17 days'),
(5, 'Láser', 5, 5, 5, 10, 'Recomendación', 'bueno', 'Ginecóloga', 'Presencial', 5, 5, 5, 'Piernas', NULL, 'Perfecta experiencia, súper recomendado', NULL, NOW() - INTERVAL '16 days'),

-- Batch 2 (30 responses)
(4, 'Mesoterapia', 4, 4, 3, 8, 'Redes sociales', 'normal', NULL, 'Presencial', 4, 4, 4, 'Abdomen', NULL, 'Muy buen servicio profesional', NULL, NOW() - INTERVAL '15 days'),
(3, 'Radiofrecuencia', 3, 3, 2, 6, 'Publicidad', 'malo', NULL, 'Presencial', 3, 3, 3, 'Glúteos', NULL, 'Regular, esperaba más', NULL, NOW() - INTERVAL '14 days'),
(5, 'Toxina Botulínica', 5, 5, 4, 9, 'Recomendación', 'bueno', NULL, 'Presencial', 5, 5, 5, 'Frente', NULL, 'Excelente atención y resultados', NULL, NOW() - INTERVAL '13 days'),
(5, 'Rellenos Dérmicos', 5, 5, 5, 10, 'Google', 'normal', NULL, 'Presencial', 5, 5, 5, 'Pómulos', NULL, 'Increíble transformación, muy feliz', NULL, NOW() - INTERVAL '12 days'),
(3, 'Peeling Químico', 4, 3, 3, 7, 'Redes sociales', 'normal', NULL, 'Presencial', 3, 4, 3, 'Rostro', NULL, 'Buenos resultados visibles', NULL, NOW() - INTERVAL '11 days'),
(4, 'Láser', 4, 4, 3, 8, 'Recomendación', 'normal', NULL, 'Presencial', 4, 4, 4, 'Axilas', NULL, 'Muy efectivo el tratamiento', NULL, NOW() - INTERVAL '10 days'),
(2, 'Otro', 3, 2, 2, 5, 'Publicidad', 'malo', NULL, 'Presencial', 2, 3, 2, 'Otro', 'Limpieza facial', 'Servicio lento pero correcto', 'Espalda', NOW() - INTERVAL '9 days'),
(5, 'Mesoterapia', 5, 5, 4, 9, 'Recomendación', 'bueno', 'Nutricionista', 'Presencial', 5, 5, 5, 'Rostro', NULL, 'Fantástica experiencia', NULL, NOW() - INTERVAL '8 days'),
(4, 'Radiofrecuencia', 4, 4, 3, 8, 'Redes sociales', 'normal', NULL, 'Presencial', 4, 4, 4, 'Abdomen', NULL, 'Muy profesional todo el equipo', NULL, NOW() - INTERVAL '7 days'),
(5, 'Toxina Botulínica', 5, 5, 5, 10, 'Google', 'bueno', NULL, 'Presencial', 5, 5, 5, 'Rostro', NULL, 'Perfecta, superó expectativas', NULL, NOW() - INTERVAL '6 days'),
(3, 'Rellenos Dérmicos', 3, 3, 2, 6, 'Publicidad', 'malo', NULL, 'Presencial', 3, 3, 3, 'Labios', NULL, 'Aceptable pero mejorable la espera', NULL, NOW() - INTERVAL '5 days'),
(5, 'Peeling Químico', 5, 5, 4, 9, 'Recomendación', 'normal', NULL, 'Presencial', 5, 5, 5, 'Rostro', NULL, 'Excelente resultado y atención', NULL, NOW() - INTERVAL '4 days'),
(3, 'Láser', 4, 3, 3, 7, 'Redes sociales', 'normal', NULL, 'Presencial', 3, 4, 3, 'Piernas', NULL, 'Buen servicio en general', NULL, NOW() - INTERVAL '3 days'),
(4, 'Mesoterapia', 4, 4, 3, 8, 'Google', 'normal', NULL, 'Presencial', 4, 4, 4, 'Glúteos', NULL, 'Muy satisfecha con resultados', NULL, NOW() - INTERVAL '2 days'),
(5, 'Radiofrecuencia', 5, 5, 5, 10, 'Recomendación', 'bueno', 'Esteticista', 'Presencial', 5, 5, 5, 'Rostro', NULL, 'Increíble servicio y resultados', NULL, NOW() - INTERVAL '1 day'),
(2, 'Otro', 2, 2, 1, 4, 'Publicidad', 'malo', NULL, 'Presencial', 2, 2, 2, 'Otro', 'Depilación', 'Muy lenta la atención', 'Brazos', NOW()),
(5, 'Toxina Botulínica', 5, 5, 4, 9, 'Redes sociales', 'bueno', NULL, 'Presencial', 5, 5, 5, 'Entrecejo', NULL, 'Excelente profesionalismo', NULL, NOW()),
(4, 'Rellenos Dérmicos', 4, 4, 3, 8, 'Recomendación', 'normal', NULL, 'Presencial', 4, 4, 4, 'Pómulos', NULL, 'Muy natural el resultado', NULL, NOW()),
(3, 'Peeling Químico', 3, 3, 3, 7, 'Google', 'normal', NULL, 'Presencial', 3, 3, 3, 'Rostro', NULL, 'Buen tratamiento facial', NULL, NOW()),
(5, 'Láser', 5, 5, 5, 10, 'Recomendación', 'bueno', 'Médico familiar', 'Presencial', 5, 5, 5, 'Axilas', NULL, 'Perfecta experiencia completa', NULL, NOW()),
(3, 'Mesoterapia', 3, 3, 2, 6, 'Publicidad', 'malo', NULL, 'Presencial', 3, 3, 3, 'Abdomen', NULL, 'Correcto pero esperaba más rapidez', NULL, NOW()),
(5, 'Radiofrecuencia', 5, 5, 4, 9, 'Redes sociales', 'normal', NULL, 'Presencial', 5, 5, 5, 'Glúteos', NULL, 'Muy efectivo y profesional', NULL, NOW()),
(4, 'Toxina Botulínica', 4, 4, 3, 8, 'Google', 'normal', NULL, 'Presencial', 4, 4, 4, 'Rostro', NULL, 'Buen resultado general', NULL, NOW()),
(2, 'Otro', 3, 2, 2, 5, 'Recomendación', 'malo', NULL, 'Presencial', 2, 3, 2, 'Otro', 'Microdermoabrasión', 'Lento pero efectivo', 'Rostro', NOW()),
(5, 'Rellenos Dérmicos', 5, 5, 5, 10, 'Redes sociales', 'bueno', NULL, 'Presencial', 5, 5, 5, 'Labios', NULL, 'Increíble resultado, muy recomendado', NULL, NOW()),
(3, 'Peeling Químico', 4, 3, 3, 7, 'Publicidad', 'normal', NULL, 'Presencial', 3, 4, 3, 'Rostro', NULL, 'Satisfecha con el servicio', NULL, NOW()),
(5, 'Láser', 5, 5, 4, 9, 'Recomendación', 'normal', NULL, 'Presencial', 5, 5, 5, 'Piernas', NULL, 'Excelente tecnología', NULL, NOW()),
(4, 'Mesoterapia', 4, 4, 3, 8, 'Google', 'normal', NULL, 'Presencial', 4, 4, 4, 'Rostro', NULL, 'Muy profesional el equipo', NULL, NOW()),
(3, 'Radiofrecuencia', 3, 3, 2, 6, 'Redes sociales', 'malo', NULL, 'Presencial', 3, 3, 3, 'Abdomen', NULL, 'Bueno pero con demoras', NULL, NOW()),
(5, 'Toxina Botulínica', 5, 5, 5, 10, 'Recomendación', 'bueno', 'Cirujano plástico', 'Presencial', 5, 5, 5, 'Frente', NULL, 'Perfecta en todos los aspectos', NULL, NOW()),

-- Batch 3 (30 responses)
(4, 'Rellenos Dérmicos', 5, 4, 3, 8, 'Google', 'normal', NULL, 'Presencial', 4, 5, 4, 'Pómulos', NULL, 'Muy satisfecha con el resultado', NULL, NOW() - INTERVAL '60 days'),
(3, 'Peeling Químico', 3, 3, 3, 7, 'Redes sociales', 'normal', NULL, 'Presencial', 3, 3, 3, 'Rostro', NULL, 'Buen tratamiento rejuvenecedor', NULL, NOW() - INTERVAL '59 days'),
(5, 'Láser', 5, 5, 4, 9, 'Recomendación', 'bueno', NULL, 'Presencial', 5, 5, 5, 'Axilas', NULL, 'Excelente y muy rápido', NULL, NOW() - INTERVAL '58 days'),
(2, 'Mesoterapia', 3, 2, 2, 5, 'Publicidad', 'malo', NULL, 'Presencial', 2, 3, 2, 'Glúteos', NULL, 'Demasiada espera para el servicio', NULL, NOW() - INTERVAL '57 days'),
(5, 'Radiofrecuencia', 5, 5, 5, 10, 'Recomendación', 'bueno', 'Fisioterapeuta', 'Presencial', 5, 5, 5, 'Rostro', NULL, 'Increíble resultado y atención', NULL, NOW() - INTERVAL '56 days'),
(4, 'Toxina Botulínica', 4, 4, 3, 8, 'Redes sociales', 'normal', NULL, 'Presencial', 4, 4, 4, 'Entrecejo', NULL, 'Muy natural el efecto', NULL, NOW() - INTERVAL '55 days'),
(3, 'Otro', 3, 3, 2, 6, 'Google', 'malo', NULL, 'Presencial', 3, 3, 3, 'Otro', 'Hidrafacial', 'Servicio correcto pero lento', 'Cuello', NOW() - INTERVAL '54 days'),
(5, 'Rellenos Dérmicos', 5, 5, 4, 9, 'Recomendación', 'normal', NULL, 'Presencial', 5, 5, 5, 'Labios', NULL, 'Fantástico resultado natural', NULL, NOW() - INTERVAL '53 days'),
(3, 'Peeling Químico', 4, 3, 3, 7, 'Publicidad', 'normal', NULL, 'Presencial', 3, 4, 3, 'Rostro', NULL, 'Buenos resultados visibles', NULL, NOW() - INTERVAL '52 days'),
(4, 'Láser', 4, 4, 3, 8, 'Redes sociales', 'normal', NULL, 'Presencial', 4, 4, 4, 'Piernas', NULL, 'Muy efectivo el tratamiento', NULL, NOW() - INTERVAL '51 days'),
(5, 'Mesoterapia', 5, 5, 5, 10, 'Google', 'bueno', NULL, 'Presencial', 5, 5, 5, 'Rostro', NULL, 'Excelente en todo sentido', NULL, NOW() - INTERVAL '50 days'),
(2, 'Radiofrecuencia', 2, 2, 1, 4, 'Publicidad', 'malo', NULL, 'Presencial', 2, 2, 2, 'Abdomen', NULL, 'Muy lenta la atención y resultados regulares', NULL, NOW() - INTERVAL '49 days'),
(5, 'Toxina Botulínica', 5, 5, 4, 9, 'Recomendación', 'bueno', NULL, 'Presencial', 5, 5, 5, 'Rostro', NULL, 'Muy profesional y efectivo', NULL, NOW() - INTERVAL '48 days'),
(4, 'Rellenos Dérmicos', 4, 4, 3, 8, 'Redes sociales', 'normal', NULL, 'Presencial', 4, 4, 4, 'Pómulos', NULL, 'Resultado muy bonito', NULL, NOW() - INTERVAL '47 days'),
(3, 'Peeling Químico', 3, 3, 3, 7, 'Google', 'normal', NULL, 'Presencial', 3, 3, 3, 'Rostro', NULL, 'Tratamiento efectivo', NULL, NOW() - INTERVAL '46 days'),
(5, 'Láser', 5, 5, 5, 10, 'Recomendación', 'bueno', 'Dermatóloga', 'Presencial', 5, 5, 5, 'Axilas', NULL, 'Perfecta experiencia, súper recomendado', NULL, NOW() - INTERVAL '75 days'),
(3, 'Mesoterapia', 3, 3, 2, 6, 'Publicidad', 'malo', NULL, 'Presencial', 3, 3, 3, 'Abdomen', NULL, 'Regular, esperaba mejor atención', NULL, NOW() - INTERVAL '74 days'),
(5, 'Radiofrecuencia', 5, 5, 4, 9, 'Redes sociales', 'normal', NULL, 'Presencial', 5, 5, 5, 'Glúteos', NULL, 'Excelente tecnología y trato', NULL, NOW() - INTERVAL '73 days'),
(4, 'Toxina Botulínica', 4, 4, 3, 8, 'Google', 'normal', NULL, 'Presencial', 4, 4, 4, 'Frente', NULL, 'Buen resultado y atención', NULL, NOW() - INTERVAL '72 days'),
(2, 'Otro', 3, 2, 2, 5, 'Recomendación', 'malo', NULL, 'Presencial', 2, 3, 2, 'Otro', 'Plasma rico en plaquetas', 'Lento pero con buenos resultados', 'Rostro', NOW() - INTERVAL '71 days'),
(5, 'Rellenos Dérmicos', 5, 5, 5, 10, 'Redes sociales', 'bueno', NULL, 'Presencial', 5, 5, 5, 'Labios', NULL, 'Increíble transformación, muy feliz', NULL, NOW() - INTERVAL '70 days'),
(3, 'Peeling Químico', 4, 3, 3, 7, 'Publicidad', 'normal', NULL, 'Presencial', 3, 4, 3, 'Rostro', NULL, 'Satisfecha con los resultados', NULL, NOW() - INTERVAL '69 days'),
(5, 'Láser', 5, 5, 4, 9, 'Recomendación', 'normal', NULL, 'Presencial', 5, 5, 5, 'Piernas', NULL, 'Excelente servicio y resultados', NULL, NOW() - INTERVAL '68 days'),
(4, 'Mesoterapia', 4, 4, 3, 8, 'Google', 'normal', NULL, 'Presencial', 4, 4, 4, 'Rostro', NULL, 'Muy profesional el equipo', NULL, NOW() - INTERVAL '67 days'),
(3, 'Radiofrecuencia', 3, 3, 2, 6, 'Redes sociales', 'malo', NULL, 'Presencial', 3, 3, 3, 'Abdomen', NULL, 'Correcto pero con demoras', NULL, NOW() - INTERVAL '66 days'),
(5, 'Toxina Botulínica', 5, 5, 5, 10, 'Recomendación', 'bueno', 'Médico estético', 'Presencial', 5, 5, 5, 'Rostro', NULL, 'Perfecta en todos los aspectos', NULL, NOW() - INTERVAL '65 days'),
(4, 'Rellenos Dérmicos', 5, 4, 3, 8, 'Publicidad', 'normal', NULL, 'Presencial', 4, 5, 4, 'Pómulos', NULL, 'Muy satisfecha con el resultado', NULL, NOW() - INTERVAL '64 days'),
(3, 'Peeling Químico', 3, 3, 3, 7, 'Google', 'normal', NULL, 'Presencial', 3, 3, 3, 'Rostro', NULL, 'Buen tratamiento facial', NULL, NOW() - INTERVAL '63 days'),
(5, 'Láser', 5, 5, 4, 9, 'Redes sociales', 'bueno', NULL, 'Presencial', 5, 5, 5, 'Axilas', NULL, 'Excelente y muy rápido', NULL, NOW() - INTERVAL '62 days'),
(2, 'Otro', 2, 2, 1, 4, 'Publicidad', 'malo', NULL, 'Presencial', 2, 2, 2, 'Otro', 'Carboxiterapia', 'Mucha espera y atención regular', 'Piernas', NOW() - INTERVAL '61 days'),

-- Batch 4 (30 responses)  
(5, 'Mesoterapia', 5, 5, 5, 10, 'Recomendación', 'bueno', 'Nutricionista', 'Presencial', 5, 5, 5, 'Rostro', NULL, 'Increíble servicio y resultados', NULL, NOW() - INTERVAL '90 days'),
(4, 'Radiofrecuencia', 4, 4, 3, 8, 'Redes sociales', 'normal', NULL, 'Presencial', 4, 4, 4, 'Glúteos', NULL, 'Muy efectivo el tratamiento', NULL, NOW() - INTERVAL '89 days'),
(3, 'Toxina Botulínica', 3, 3, 2, 6, 'Google', 'malo', NULL, 'Presencial', 3, 3, 3, 'Entrecejo', NULL, 'Bueno pero con esperas largas', NULL, NOW() - INTERVAL '88 days'),
(5, 'Rellenos Dérmicos', 5, 5, 4, 9, 'Publicidad', 'normal', NULL, 'Presencial', 5, 5, 5, 'Labios', NULL, 'Fantástico resultado natural', NULL, NOW() - INTERVAL '87 days'),
(3, 'Peeling Químico', 4, 3, 3, 7, 'Recomendación', 'normal', NULL, 'Presencial', 3, 4, 3, 'Rostro', NULL, 'Buenos resultados visibles', NULL, NOW() - INTERVAL '86 days'),
(4, 'Láser', 4, 4, 3, 8, 'Redes sociales', 'normal', NULL, 'Presencial', 4, 4, 4, 'Piernas', NULL, 'Muy profesional todo', NULL, NOW() - INTERVAL '85 days'),
(2, 'Otro', 3, 2, 2, 5, 'Google', 'malo', NULL, 'Presencial', 2, 3, 2, 'Otro', 'Drenaje linfático', 'Servicio lento pero efectivo', 'Abdomen', NOW() - INTERVAL '84 days'),
(5, 'Mesoterapia', 5, 5, 5, 10, 'Recomendación', 'bueno', 'Esteticista', 'Presencial', 5, 5, 5, 'Abdomen', NULL, 'Excelente en todo sentido', NULL, NOW() - INTERVAL '83 days'),
(4, 'Radiofrecuencia', 4, 4, 3, 8, 'Publicidad', 'normal', NULL, 'Presencial', 4, 4, 4, 'Rostro', NULL, 'Buen servicio profesional', NULL, NOW() - INTERVAL '82 days'),
(3, 'Toxina Botulínica', 3, 3, 3, 7, 'Redes sociales', 'normal', NULL, 'Presencial', 3, 3, 3, 'Rostro', NULL, 'Satisfecha con el resultado', NULL, NOW() - INTERVAL '81 days'),
(5, 'Rellenos Dérmicos', 5, 5, 4, 9, 'Google', 'bueno', NULL, 'Presencial', 5, 5, 5, 'Pómulos', NULL, 'Excelente resultado y atención', NULL, NOW() - INTERVAL '80 days'),
(3, 'Peeling Químico', 3, 3, 2, 6, 'Recomendación', 'malo', NULL, 'Presencial', 3, 3, 3, 'Rostro', NULL, 'Regular, esperaba más rapidez', NULL, NOW() - INTERVAL '79 days'),
(4, 'Láser', 4, 4, 3, 8, 'Publicidad', 'normal', NULL, 'Presencial', 4, 4, 4, 'Axilas', NULL, 'Muy efectivo y rápido', NULL, NOW() - INTERVAL '78 days'),
(5, 'Mesoterapia', 5, 5, 5, 10, 'Redes sociales', 'bueno', NULL, 'Presencial', 5, 5, 5, 'Glúteos', NULL, 'Perfecta experiencia completa', NULL, NOW() - INTERVAL '77 days'),
(2, 'Otro', 2, 2, 1, 4, 'Google', 'malo', NULL, 'Presencial', 2, 2, 2, 'Otro', 'Ultrasonido', 'Muy lenta la atención', 'Abdomen', NOW() - INTERVAL '76 days'),
(5, 'Radiofrecuencia', 5, 5, 4, 9, 'Recomendación', 'normal', NULL, 'Presencial', 5, 5, 5, 'Rostro', NULL, 'Excelente tecnología', NULL, NOW() - INTERVAL '105 days'),
(4, 'Toxina Botulínica', 4, 4, 3, 8, 'Redes sociales', 'normal', NULL, 'Presencial', 4, 4, 4, 'Frente', NULL, 'Muy natural el resultado', NULL, NOW() - INTERVAL '104 days'),
(3, 'Rellenos Dérmicos', 4, 3, 3, 7, 'Publicidad', 'normal', NULL, 'Presencial', 3, 4, 3, 'Labios', NULL, 'Buen resultado general', NULL, NOW() - INTERVAL '103 days'),
(5, 'Peeling Químico', 5, 5, 5, 10, 'Google', 'bueno', NULL, 'Presencial', 5, 5, 5, 'Rostro', NULL, 'Increíble transformación', NULL, NOW() - INTERVAL '102 days'),
(3, 'Láser', 3, 3, 2, 6, 'Recomendación', 'malo', NULL, 'Presencial', 3, 3, 3, 'Piernas', NULL, 'Correcto pero con demoras', NULL, NOW() - INTERVAL '101 days'),
(5, 'Mesoterapia', 5, 5, 4, 9, 'Redes sociales', 'normal', NULL, 'Presencial', 5, 5, 5, 'Rostro', NULL, 'Muy satisfecha con todo', NULL, NOW() - INTERVAL '100 days'),
(4, 'Radiofrecuencia', 4, 4, 3, 8, 'Publicidad', 'normal', NULL, 'Presencial', 4, 4, 4, 'Abdomen', NULL, 'Profesional y efectivo', NULL, NOW() - INTERVAL '99 days'),
(2, 'Otro', 3, 2, 2, 5, 'Google', 'malo', NULL, 'Presencial', 2, 3, 2, 'Otro', 'Radiofrecuencia facial', 'Lento pero con resultados', 'Cuello', NOW() - INTERVAL '98 days'),
(5, 'Toxina Botulínica', 5, 5, 5, 10, 'Recomendación', 'bueno', 'Dermatóloga', 'Presencial', 5, 5, 5, 'Rostro', NULL, 'Perfecta en todos los aspectos', NULL, NOW() - INTERVAL '97 days'),
(3, 'Rellenos Dérmicos', 3, 3, 3, 7, 'Redes sociales', 'normal', NULL, 'Presencial', 3, 3, 3, 'Pómulos', NULL, 'Tratamiento efectivo', NULL, NOW() - INTERVAL '96 days'),
(4, 'Peeling Químico', 4, 4, 3, 8, 'Publicidad', 'normal', NULL, 'Presencial', 4, 4, 4, 'Rostro', NULL, 'Muy buen servicio', NULL, NOW() - INTERVAL '95 days'),
(5, 'Láser', 5, 5, 4, 9, 'Google', 'bueno', NULL, 'Presencial', 5, 5, 5, 'Axilas', NULL, 'Excelente y rápido', NULL, NOW() - INTERVAL '94 days'),
(3, 'Mesoterapia', 3, 3, 2, 6, 'Recomendación', 'malo', NULL, 'Presencial', 3, 3, 3, 'Glúteos', NULL, 'Bueno pero mejorable', NULL, NOW() - INTERVAL '93 days'),
(5, 'Radiofrecuencia', 5, 5, 5, 10, 'Redes sociales', 'bueno', NULL, 'Presencial', 5, 5, 5, 'Rostro', NULL, 'Increíble resultado', NULL, NOW() - INTERVAL '92 days'),
(4, 'Toxina Botulínica', 4, 4, 3, 8, 'Publicidad', 'normal', NULL, 'Presencial', 4, 4, 4, 'Entrecejo', NULL, 'Muy satisfecha', NULL, NOW() - INTERVAL '91 days');