-- Eliminar todas las respuestas actuales
DELETE FROM survey_responses;

-- Insertar 120 respuestas realistas con las opciones exactas del formulario
INSERT INTO survey_responses (
  website_design_rating,
  communication_clarity,
  appointment_type,
  treatment_type,
  other_treatment,
  body_area,
  other_body_area,
  reception_friendliness,
  waiting_time,
  clinic_environment,
  doctor_listening,
  explanation_clarity,
  consultation_time,
  nps_score,
  additional_comments,
  how_did_you_know_us,
  referral_details,
  created_at
) VALUES 
-- Batch 1 (40 responses)
(2, 3, 'presencial', 'fisioterapia', NULL, 'rodilla', NULL, 3, 'bueno', 3, 3, 3, 3, 9, 'Excelente atención, muy profesional y efectivo', 'Recomendación médica', NULL, NOW() - INTERVAL '2 days'),
(3, 2, 'presencial', 'osteopatia', NULL, 'columna_lumbar', NULL, 2, 'normal', 2, 3, 2, 2, 7, 'Buen tratamiento pero la sala de espera estaba un poco llena', 'Google', NULL, NOW() - INTERVAL '5 days'),
(1, 2, 'telematica', 'readaptacion', NULL, 'hombro', NULL, 2, 'normal', 2, 2, 2, 2, 6, 'La conexión se cortó un par de veces', 'Redes sociales', NULL, NOW() - INTERVAL '8 days'),
(3, 3, 'presencial', 'puncion_seca', NULL, 'columna_cervical', NULL, 3, 'bueno', 3, 3, 3, 3, 10, 'Increíble resultado! El dolor desapareció completamente', 'Familiar', NULL, NOW() - INTERVAL '12 days'),
(2, 2, 'presencial', 'electrolisis', NULL, 'pie', NULL, 2, 'malo', 1, 2, 2, 1, 4, 'Mucha espera y la sala no estaba muy limpia', 'Seguro médico', NULL, NOW() - INTERVAL '15 days'),
(3, 3, 'presencial', 'terapia_manual', NULL, 'mano', NULL, 3, 'bueno', 3, 3, 2, 3, 8, 'Muy buen trato y explicaciones claras', 'Recomendación', NULL, NOW() - INTERVAL '18 days'),
(2, 1, 'telematica', 'fisioterapia', NULL, 'codo', NULL, 1, 'normal', 1, 1, 1, 1, 3, 'No quedé muy satisfecho con la consulta online', 'Buscador internet', NULL, NOW() - INTERVAL '22 days'),
(3, 3, 'presencial', 'otro', 'Drenaje linfático', 'otra', 'Tobillo', 3, 'bueno', 3, 3, 3, 3, 9, 'Tratamiento muy específico y efectivo para mi lesión', 'Fisioterapeuta conocido', NULL, NOW() - INTERVAL '25 days'),
(2, 2, 'presencial', 'osteopatia', NULL, 'columna_dorsal', NULL, 2, 'normal', 2, 2, 2, 2, 7, 'Correcto, cumplió con mis expectativas', 'Clínica privada', NULL, NOW() - INTERVAL '28 days'),
(3, 2, 'presencial', 'readaptacion', NULL, 'rodilla', NULL, 3, 'bueno', 2, 3, 3, 2, 8, 'Muy contento con la evolución de mi rodilla', 'Traumatólogo', NULL, NOW() - INTERVAL '32 days'),
(1, 1, 'telematica', 'fisioterapia', NULL, 'hombro', NULL, 1, 'malo', 1, 1, 2, 1, 2, 'Problemas técnicos constantes, no pude seguir bien', 'Internet', NULL, NOW() - INTERVAL '35 days'),
(3, 3, 'presencial', 'puncion_seca', NULL, 'columna_lumbar', NULL, 3, 'bueno', 3, 3, 3, 3, 10, 'Fantástico! Por fin encontré solución a mi dolor lumbar', 'Médico de familia', NULL, NOW() - INTERVAL '38 days'),
(2, 2, 'presencial', 'electrolisis', NULL, 'columna_cervical', NULL, 2, 'normal', 2, 2, 2, 2, 6, 'Bien en general, aunque esperaba más mejoría', 'Compañero trabajo', NULL, NOW() - INTERVAL '42 days'),
(3, 3, 'presencial', 'terapia_manual', NULL, 'pie', NULL, 3, 'bueno', 3, 3, 3, 3, 9, 'Excelente técnica y muy buen trato personal', 'Recomendación', NULL, NOW() - INTERVAL '45 days'),
(2, 2, 'telematica', 'osteopatia', NULL, 'mano', NULL, 2, 'normal', 2, 2, 2, 2, 5, 'La consulta online está bien pero prefiero presencial', 'Página web', NULL, NOW() - INTERVAL '48 days'),
(3, 3, 'presencial', 'fisioterapia', NULL, 'codo', NULL, 3, 'bueno', 3, 3, 3, 3, 9, 'Muy profesional y las instalaciones impecables', 'Seguro', NULL, NOW() - INTERVAL '52 days'),
(1, 2, 'presencial', 'readaptacion', NULL, 'otra', 'Cadera', 1, 'malo', 2, 2, 1, 2, 4, 'La espera fue muy larga y no me sentí bien atendido', 'Mutua', NULL, NOW() - INTERVAL '55 days'),
(3, 2, 'presencial', 'otro', 'Masaje deportivo', 'rodilla', NULL, 3, 'bueno', 2, 3, 3, 3, 8, 'Muy buen masaje, me ayudó mucho con la recuperación', 'Entrenador', NULL, NOW() - INTERVAL '58 days'),
(2, 3, 'telematica', 'fisioterapia', NULL, 'hombro', NULL, 3, 'bueno', 3, 3, 2, 2, 7, 'Buena consulta online, bien organizada', 'Google', NULL, NOW() - INTERVAL '62 days'),
(3, 3, 'presencial', 'puncion_seca', NULL, 'columna_dorsal', NULL, 3, 'bueno', 3, 3, 3, 3, 10, 'Impresionante resultado, recomiendo 100%', 'Fisio anterior', NULL, NOW() - INTERVAL '65 days'),
(2, 1, 'presencial', 'electrolisis', NULL, 'columna_lumbar', NULL, 1, 'malo', 1, 1, 1, 1, 3, 'No me gustó nada, no volveré', 'Anuncio', NULL, NOW() - INTERVAL '68 days'),
(3, 3, 'presencial', 'terapia_manual', NULL, 'columna_cervical', NULL, 3, 'bueno', 3, 3, 3, 3, 9, 'Excelente profesional, muy recomendable', 'Médico', NULL, NOW() - INTERVAL '72 days'),
(2, 2, 'telematica', 'osteopatia', NULL, 'pie', NULL, 2, 'normal', 2, 2, 2, 2, 6, 'Está bien la modalidad online para seguimiento', 'Clínica', NULL, NOW() - INTERVAL '75 days'),
(3, 2, 'presencial', 'fisioterapia', NULL, 'mano', NULL, 2, 'normal', 3, 3, 3, 3, 8, 'Muy buen fisioterapeuta, explica todo muy bien', 'Familiar', NULL, NOW() - INTERVAL '78 days'),
(1, 1, 'presencial', 'readaptacion', NULL, 'codo', NULL, 1, 'malo', 1, 1, 1, 1, 2, 'Muy mala experiencia, instalaciones descuidadas', 'Internet', NULL, NOW() - INTERVAL '82 days'),
(3, 3, 'presencial', 'otro', 'Vendaje neuromuscular', 'rodilla', NULL, 3, 'bueno', 3, 3, 3, 3, 9, 'Excelente técnica de vendaje, muy efectivo', 'Deportista', NULL, NOW() - INTERVAL '85 days'),
(2, 2, 'telematica', 'puncion_seca', NULL, 'hombro', NULL, 2, 'normal', 2, 2, 2, 2, 6, 'Consulta online correcta para evaluar evolución', 'Teléfono', NULL, NOW() - INTERVAL '88 days'),
(3, 3, 'presencial', 'electrolisis', NULL, 'otra', 'Gemelo', 3, 'bueno', 3, 3, 3, 3, 10, 'Increíble técnica, dolor desaparecido', 'Traumatólogo', NULL, NOW() - INTERVAL '92 days'),
(2, 2, 'presencial', 'terapia_manual', NULL, 'columna_dorsal', NULL, 2, 'normal', 2, 2, 2, 2, 7, 'Tratamiento correcto, mejoré bastante', 'Seguro médico', NULL, NOW() - INTERVAL '95 days'),
(3, 3, 'presencial', 'osteopatia', NULL, 'columna_lumbar', NULL, 3, 'bueno', 3, 3, 3, 3, 9, 'Muy buen osteópata, manos expertas', 'Recomendación', NULL, NOW() - INTERVAL '98 days'),
(1, 2, 'telematica', 'fisioterapia', NULL, 'columna_cervical', NULL, 1, 'malo', 2, 1, 1, 1, 3, 'Conexión deficiente, no pude aprovechar la sesión', 'App móvil', NULL, NOW() - INTERVAL '102 days'),
(3, 2, 'presencial', 'readaptacion', NULL, 'pie', NULL, 3, 'bueno', 2, 3, 3, 3, 8, 'Muy buen programa de readaptación personalizado', 'Entrenador personal', NULL, NOW() - INTERVAL '105 days'),
(2, 3, 'presencial', 'otro', 'Ejercicio terapéutico', 'mano', NULL, 2, 'normal', 3, 3, 2, 2, 7, 'Buenos ejercicios para la recuperación', 'Cirujano', NULL, NOW() - INTERVAL '108 days'),
(3, 3, 'presencial', 'puncion_seca', NULL, 'codo', NULL, 3, 'bueno', 3, 3, 3, 3, 10, 'Excelente técnica, resultado inmediato', 'Médico deportivo', NULL, NOW() - INTERVAL '112 days'),
(2, 1, 'presencial', 'electrolisis', NULL, 'rodilla', NULL, 1, 'malo', 1, 2, 1, 1, 4, 'No me gustó el trato recibido', 'Folleto', NULL, NOW() - INTERVAL '115 days'),
(3, 3, 'telematica', 'terapia_manual', NULL, 'hombro', NULL, 3, 'bueno', 3, 3, 3, 3, 8, 'Buena consulta online con ejercicios personalizados', 'Página web', NULL, NOW() - INTERVAL '118 days'),
(2, 2, 'presencial', 'osteopatia', NULL, 'otra', 'Costillas', 2, 'normal', 2, 2, 2, 2, 6, 'Tratamiento específico, mejoría gradual', 'Médico general', NULL, NOW() - INTERVAL '122 days'),
(3, 3, 'presencial', 'fisioterapia', NULL, 'columna_dorsal', NULL, 3, 'bueno', 3, 3, 3, 3, 9, 'Fantástico profesional, muy recomendable', 'Compañero', NULL, NOW() - INTERVAL '125 days'),
(1, 1, 'telematica', 'readaptacion', NULL, 'columna_lumbar', NULL, 1, 'malo', 1, 1, 1, 1, 2, 'Muy mala conexión, no pude hacer nada', 'Buscador', NULL, NOW() - INTERVAL '128 days'),
(3, 2, 'presencial', 'otro', 'Terapia con ondas de choque', 'columna_cervical', NULL, 3, 'bueno', 2, 3, 3, 3, 9, 'Nueva técnica muy efectiva para mi problema', 'Especialista', NULL, NOW() - INTERVAL '132 days'),

-- Batch 2 (40 responses)
(2, 2, 'presencial', 'puncion_seca', NULL, 'pie', NULL, 2, 'normal', 2, 2, 2, 2, 6, 'Tratamiento eficaz aunque algo doloroso', 'Podólogo', NULL, NOW() - INTERVAL '135 days'),
(3, 3, 'presencial', 'electrolisis', NULL, 'mano', NULL, 3, 'bueno', 3, 3, 3, 3, 9, 'Excelente técnica para mi tendinitis', 'Traumatólogo', NULL, NOW() - INTERVAL '138 days'),
(2, 2, 'telematica', 'terapia_manual', NULL, 'codo', NULL, 2, 'normal', 2, 2, 2, 2, 5, 'Consulta online útil pero limitada', 'Seguro', NULL, NOW() - INTERVAL '142 days'),
(3, 3, 'presencial', 'osteopatia', NULL, 'rodilla', NULL, 3, 'bueno', 3, 3, 3, 3, 10, 'Increíble mejoría en una sola sesión', 'Recomendación', NULL, NOW() - INTERVAL '145 days'),
(1, 2, 'presencial', 'fisioterapia', NULL, 'hombro', NULL, 1, 'malo', 2, 1, 2, 1, 3, 'Esperé más de una hora, muy desorganizado', 'Mutua laboral', NULL, NOW() - INTERVAL '148 days'),
(3, 2, 'presencial', 'readaptacion', NULL, 'otra', 'Muñeca', 2, 'normal', 3, 3, 3, 3, 8, 'Buen programa de ejercicios adaptado', 'Fisio deportivo', NULL, NOW() - INTERVAL '152 days'),
(2, 3, 'telematica', 'otro', 'Pilates terapéutico', 'columna_dorsal', NULL, 3, 'bueno', 3, 3, 2, 2, 7, 'Buenas clases online de pilates correctivo', 'Google', NULL, NOW() - INTERVAL '155 days'),
(3, 3, 'presencial', 'puncion_seca', NULL, 'columna_lumbar', NULL, 3, 'bueno', 3, 3, 3, 3, 10, 'Resultados espectaculares, recomiendo totalmente', 'Médico de cabecera', NULL, NOW() - INTERVAL '158 days'),
(2, 1, 'presencial', 'electrolisis', NULL, 'columna_cervical', NULL, 1, 'malo', 1, 1, 1, 1, 3, 'Instalaciones poco cuidadas y mal trato', 'Anuncio prensa', NULL, NOW() - INTERVAL '162 days'),
(3, 3, 'presencial', 'terapia_manual', NULL, 'pie', NULL, 3, 'bueno', 3, 3, 3, 3, 9, 'Manos expertas, gran profesional', 'Familiar', NULL, NOW() - INTERVAL '165 days'),
(2, 2, 'telematica', 'osteopatia', NULL, 'mano', NULL, 2, 'normal', 2, 2, 2, 2, 6, 'Consulta correcta para seguimiento', 'App', NULL, NOW() - INTERVAL '168 days'),
(3, 2, 'presencial', 'fisioterapia', NULL, 'codo', NULL, 2, 'normal', 3, 3, 3, 3, 8, 'Muy buen fisio, explica todo perfectamente', 'Centro médico', NULL, NOW() - INTERVAL '172 days'),
(1, 1, 'presencial', 'readaptacion', NULL, 'rodilla', NULL, 1, 'malo', 1, 1, 1, 1, 2, 'Pésima organización y trato desagradable', 'Internet', NULL, NOW() - INTERVAL '175 days'),
(3, 3, 'presencial', 'otro', 'Dry needling', 'hombro', NULL, 3, 'bueno', 3, 3, 3, 3, 9, 'Técnica muy avanzada y efectiva', 'Deportólogo', NULL, NOW() - INTERVAL '178 days'),
(2, 2, 'telematica', 'puncion_seca', NULL, 'otra', 'Pantorrilla', 2, 'normal', 2, 2, 2, 2, 6, 'Consulta online para valorar puntos gatillo', 'Teléfono', NULL, NOW() - INTERVAL '182 days'),
(3, 3, 'presencial', 'electrolisis', NULL, 'columna_dorsal', NULL, 3, 'bueno', 3, 3, 3, 3, 10, 'Increíble técnica, dolor desaparecido totalmente', 'Neurocirujano', NULL, NOW() - INTERVAL '185 days'),
(2, 2, 'presencial', 'terapia_manual', NULL, 'columna_lumbar', NULL, 2, 'normal', 2, 2, 2, 2, 7, 'Tratamiento manual correcto y efectivo', 'Seguro médico', NULL, NOW() - INTERVAL '188 days'),
(3, 3, 'presencial', 'osteopatia', NULL, 'columna_cervical', NULL, 3, 'bueno', 3, 3, 3, 3, 9, 'Excelente osteópata, muy recomendable', 'Recomendación', NULL, NOW() - INTERVAL '192 days'),
(1, 2, 'telematica', 'fisioterapia', NULL, 'pie', NULL, 1, 'malo', 2, 1, 1, 1, 3, 'Muchos problemas técnicos durante la sesión', 'Página web', NULL, NOW() - INTERVAL '195 days'),
(3, 2, 'presencial', 'readaptacion', NULL, 'mano', NULL, 3, 'bueno', 2, 3, 3, 3, 8, 'Buen programa de readaptación funcional', 'Cirujano mano', NULL, NOW() - INTERVAL '198 days'),
(2, 3, 'presencial', 'otro', 'Kinesiotaping', 'codo', NULL, 2, 'normal', 3, 3, 2, 2, 7, 'Buen vendaje funcional, me ayudó', 'Entrenador', NULL, NOW() - INTERVAL '202 days'),
(3, 3, 'presencial', 'puncion_seca', NULL, 'rodilla', NULL, 3, 'bueno', 3, 3, 3, 3, 10, 'Técnica impresionante, resultado inmediato', 'Médico deportivo', NULL, NOW() - INTERVAL '205 days'),
(2, 1, 'presencial', 'electrolisis', NULL, 'hombro', NULL, 1, 'malo', 1, 2, 1, 1, 4, 'No me transmitió confianza el profesional', 'Folleto', NULL, NOW() - INTERVAL '208 days'),
(3, 3, 'telematica', 'terapia_manual', NULL, 'otra', 'Mandíbula', 3, 'bueno', 3, 3, 3, 3, 8, 'Buena consulta para mi disfunción ATM', 'Dentista', NULL, NOW() - INTERVAL '212 days'),
(2, 2, 'presencial', 'osteopatia', NULL, 'columna_dorsal', NULL, 2, 'normal', 2, 2, 2, 2, 6, 'Tratamiento osteopático correcto', 'Médico general', NULL, NOW() - INTERVAL '215 days'),
(3, 3, 'presencial', 'fisioterapia', NULL, 'columna_lumbar', NULL, 3, 'bueno', 3, 3, 3, 3, 9, 'Excelente fisioterapeuta, muy profesional', 'Compañero trabajo', NULL, NOW() - INTERVAL '218 days'),
(1, 1, 'telematica', 'readaptacion', NULL, 'columna_cervical', NULL, 1, 'malo', 1, 1, 1, 1, 2, 'Conexión pésima, no pude hacer ejercicios', 'Buscador web', NULL, NOW() - INTERVAL '222 days'),
(3, 2, 'presencial', 'otro', 'Magnetoterapia', 'pie', NULL, 3, 'bueno', 2, 3, 3, 3, 9, 'Tratamiento con magnetoterapia muy efectivo', 'Podólogo', NULL, NOW() - INTERVAL '225 days'),
(2, 2, 'presencial', 'puncion_seca', NULL, 'mano', NULL, 2, 'normal', 2, 2, 2, 2, 6, 'Técnica algo molesta pero efectiva', 'Traumatólogo', NULL, NOW() - INTERVAL '228 days'),
(3, 3, 'presencial', 'electrolisis', NULL, 'codo', NULL, 3, 'bueno', 3, 3, 3, 3, 9, 'Excelente para mi epicondilitis', 'Recomendación', NULL, NOW() - INTERVAL '232 days'),
(2, 2, 'telematica', 'terapia_manual', NULL, 'rodilla', NULL, 2, 'normal', 2, 2, 2, 2, 5, 'Consulta online limitada para terapia manual', 'Seguro', NULL, NOW() - INTERVAL '235 days'),
(3, 3, 'presencial', 'osteopatia', NULL, 'hombro', NULL, 3, 'bueno', 3, 3, 3, 3, 10, 'Resultado increíble en pocas sesiones', 'Médico deportivo', NULL, NOW() - INTERVAL '238 days'),
(1, 2, 'presencial', 'fisioterapia', NULL, 'otra', 'Sacroilíaca', 1, 'malo', 2, 1, 2, 1, 3, 'Mucha desorganización, no volveré', 'Mutua', NULL, NOW() - INTERVAL '242 days'),
(3, 2, 'presencial', 'readaptacion', NULL, 'columna_dorsal', NULL, 2, 'normal', 3, 3, 3, 3, 8, 'Buen programa de ejercicios correctivos', 'Entrenador personal', NULL, NOW() - INTERVAL '245 days'),
(2, 3, 'telematica', 'otro', 'Escuela de espalda', 'columna_lumbar', NULL, 3, 'bueno', 3, 3, 2, 2, 7, 'Buena educación postural online', 'Google', NULL, NOW() - INTERVAL '248 days'),
(3, 3, 'presencial', 'puncion_seca', NULL, 'columna_cervical', NULL, 3, 'bueno', 3, 3, 3, 3, 10, 'Increíble para mi cervicalgia', 'Neurólogo', NULL, NOW() - INTERVAL '252 days'),
(2, 1, 'presencial', 'electrolisis', NULL, 'pie', NULL, 1, 'malo', 1, 1, 1, 1, 3, 'Instalaciones descuidadas y mal trato', 'Anuncio', NULL, NOW() - INTERVAL '255 days'),
(3, 3, 'presencial', 'terapia_manual', NULL, 'mano', NULL, 3, 'bueno', 3, 3, 3, 3, 9, 'Manos expertas, gran profesional', 'Cirujano', NULL, NOW() - INTERVAL '258 days'),
(2, 2, 'telematica', 'osteopatia', NULL, 'codo', NULL, 2, 'normal', 2, 2, 2, 2, 6, 'Consulta online adecuada', 'App móvil', NULL, NOW() - INTERVAL '262 days'),
(3, 2, 'presencial', 'fisioterapia', NULL, 'rodilla', NULL, 2, 'normal', 3, 3, 3, 3, 8, 'Muy buen profesional y trato', 'Centro de salud', NULL, NOW() - INTERVAL '265 days'),

-- Batch 3 (40 responses - últimas)
(1, 1, 'presencial', 'readaptacion', NULL, 'hombro', NULL, 1, 'malo', 1, 1, 1, 1, 2, 'Experiencia muy negativa', 'Internet', NULL, NOW() - INTERVAL '268 days'),
(3, 3, 'presencial', 'otro', 'Ultrasonoterapia', 'otra', 'Tendón Aquiles', 3, 'bueno', 3, 3, 3, 3, 9, 'Tratamiento con ultrasonidos muy efectivo', 'Podólogo deportivo', NULL, NOW() - INTERVAL '272 days'),
(2, 2, 'telematica', 'puncion_seca', NULL, 'columna_dorsal', NULL, 2, 'normal', 2, 2, 2, 2, 6, 'Consulta online para seguimiento', 'Teléfono', NULL, NOW() - INTERVAL '275 days'),
(3, 3, 'presencial', 'electrolisis', NULL, 'columna_lumbar', NULL, 3, 'bueno', 3, 3, 3, 3, 10, 'Excelente para mi ciática', 'Traumatólogo', NULL, NOW() - INTERVAL '278 days'),
(2, 2, 'presencial', 'terapia_manual', NULL, 'columna_cervical', NULL, 2, 'normal', 2, 2, 2, 2, 7, 'Terapia manual efectiva', 'Seguro médico', NULL, NOW() - INTERVAL '282 days'),
(3, 3, 'presencial', 'osteopatia', NULL, 'pie', NULL, 3, 'bueno', 3, 3, 3, 3, 9, 'Osteópata excelente', 'Recomendación', NULL, NOW() - INTERVAL '285 days'),
(1, 2, 'telematica', 'fisioterapia', NULL, 'mano', NULL, 1, 'malo', 2, 1, 1, 1, 3, 'Problemas de conexión constantes', 'Página web', NULL, NOW() - INTERVAL '288 days'),
(3, 2, 'presencial', 'readaptacion', NULL, 'codo', NULL, 3, 'bueno', 2, 3, 3, 3, 8, 'Buen programa de readaptación', 'Fisio anterior', NULL, NOW() - INTERVAL '292 days'),
(2, 3, 'presencial', 'otro', 'Electroterapia', 'rodilla', NULL, 2, 'normal', 3, 3, 2, 2, 7, 'Electroterapia útil para mi lesión', 'Entrenador', NULL, NOW() - INTERVAL '295 days'),
(3, 3, 'presencial', 'puncion_seca', NULL, 'hombro', NULL, 3, 'bueno', 3, 3, 3, 3, 10, 'Técnica increíble', 'Médico deportivo', NULL, NOW() - INTERVAL '298 days'),
(2, 1, 'presencial', 'electrolisis', NULL, 'otra', 'Isquiotibiales', 1, 'malo', 1, 2, 1, 1, 4, 'No me gustó el trato', 'Folleto', NULL, NOW() - INTERVAL '302 days'),
(3, 3, 'telematica', 'terapia_manual', NULL, 'columna_dorsal', NULL, 3, 'bueno', 3, 3, 3, 3, 8, 'Buena consulta online', 'Google', NULL, NOW() - INTERVAL '305 days'),
(2, 2, 'presencial', 'osteopatia', NULL, 'columna_lumbar', NULL, 2, 'normal', 2, 2, 2, 2, 6, 'Tratamiento osteopático correcto', 'Médico', NULL, NOW() - INTERVAL '308 days'),
(3, 3, 'presencial', 'fisioterapia', NULL, 'columna_cervical', NULL, 3, 'bueno', 3, 3, 3, 3, 9, 'Fisioterapeuta excelente', 'Familiar', NULL, NOW() - INTERVAL '312 days'),
(1, 1, 'telematica', 'readaptacion', NULL, 'pie', NULL, 1, 'malo', 1, 1, 1, 1, 2, 'Muy mala conexión', 'Buscador', NULL, NOW() - INTERVAL '315 days'),
(3, 2, 'presencial', 'otro', 'Crioterapia', 'mano', NULL, 3, 'bueno', 2, 3, 3, 3, 9, 'Crioterapia muy efectiva', 'Especialista', NULL, NOW() - INTERVAL '318 days'),
(2, 2, 'presencial', 'puncion_seca', NULL, 'codo', NULL, 2, 'normal', 2, 2, 2, 2, 6, 'Técnica efectiva aunque molesta', 'Traumatólogo', NULL, NOW() - INTERVAL '322 days'),
(3, 3, 'presencial', 'electrolisis', NULL, 'rodilla', NULL, 3, 'bueno', 3, 3, 3, 3, 9, 'Excelente para mi condromalacia', 'Deportólogo', NULL, NOW() - INTERVAL '325 days'),
(2, 2, 'telematica', 'terapia_manual', NULL, 'hombro', NULL, 2, 'normal', 2, 2, 2, 2, 5, 'Consulta online limitada', 'Seguro', NULL, NOW() - INTERVAL '328 days'),
(3, 3, 'presencial', 'osteopatia', NULL, 'otra', 'ATM', 3, 'bueno', 3, 3, 3, 3, 10, 'Increíble para mi disfunción', 'Dentista', NULL, NOW() - INTERVAL '332 days'),
(1, 2, 'presencial', 'fisioterapia', NULL, 'columna_dorsal', NULL, 1, 'malo', 2, 1, 2, 1, 3, 'Desorganización total', 'Mutua', NULL, NOW() - INTERVAL '335 days'),
(3, 2, 'presencial', 'readaptacion', NULL, 'columna_lumbar', NULL, 2, 'normal', 3, 3, 3, 3, 8, 'Buen programa personalizado', 'Entrenador', NULL, NOW() - INTERVAL '338 days'),
(2, 3, 'telematica', 'otro', 'Reeducación postural', 'columna_cervical', NULL, 3, 'bueno', 3, 3, 2, 2, 7, 'Buena educación postural', 'Google', NULL, NOW() - INTERVAL '342 days'),
(3, 3, 'presencial', 'puncion_seca', NULL, 'pie', NULL, 3, 'bueno', 3, 3, 3, 3, 10, 'Resultado espectacular', 'Podólogo', NULL, NOW() - INTERVAL '345 days'),
(2, 1, 'presencial', 'electrolisis', NULL, 'mano', NULL, 1, 'malo', 1, 1, 1, 1, 3, 'Mala experiencia general', 'Anuncio', NULL, NOW() - INTERVAL '348 days'),
(3, 3, 'presencial', 'terapia_manual', NULL, 'codo', NULL, 3, 'bueno', 3, 3, 3, 3, 9, 'Terapia manual excelente', 'Recomendación', NULL, NOW() - INTERVAL '352 days'),
(2, 2, 'telematica', 'osteopatia', NULL, 'rodilla', NULL, 2, 'normal', 2, 2, 2, 2, 6, 'Consulta online adecuada', 'App', NULL, NOW() - INTERVAL '355 days'),
(3, 2, 'presencial', 'fisioterapia', NULL, 'hombro', NULL, 2, 'normal', 3, 3, 3, 3, 8, 'Muy buen fisioterapeuta', 'Centro médico', NULL, NOW() - INTERVAL '358 days'),
(1, 1, 'presencial', 'readaptacion', NULL, 'otra', 'Coxis', 1, 'malo', 1, 1, 1, 1, 2, 'Experiencia pésima', 'Internet', NULL, NOW() - INTERVAL '362 days'),
(3, 3, 'presencial', 'otro', 'Diatermia', 'columna_dorsal', NULL, 3, 'bueno', 3, 3, 3, 3, 9, 'Diatermia muy efectiva', 'Especialista', NULL, NOW() - INTERVAL '365 days'),
(2, 2, 'telematica', 'puncion_seca', NULL, 'columna_lumbar', NULL, 2, 'normal', 2, 2, 2, 2, 6, 'Seguimiento online correcto', 'Teléfono', NULL, NOW() - INTERVAL '368 days'),
(3, 3, 'presencial', 'electrolisis', NULL, 'columna_cervical', NULL, 3, 'bueno', 3, 3, 3, 3, 10, 'Increíble para mi tortícolis', 'Neurólogo', NULL, NOW() - INTERVAL '372 days'),
(2, 2, 'presencial', 'terapia_manual', NULL, 'pie', NULL, 2, 'normal', 2, 2, 2, 2, 7, 'Terapia manual efectiva', 'Podólogo', NULL, NOW() - INTERVAL '375 days'),
(3, 3, 'presencial', 'osteopatia', NULL, 'mano', NULL, 3, 'bueno', 3, 3, 3, 3, 9, 'Osteópata excelente', 'Traumatólogo', NULL, NOW() - INTERVAL '378 days'),
(1, 2, 'telematica', 'fisioterapia', NULL, 'codo', NULL, 1, 'malo', 2, 1, 1, 1, 3, 'Problemas técnicos graves', 'Página web', NULL, NOW() - INTERVAL '382 days'),
(3, 2, 'presencial', 'readaptacion', NULL, 'rodilla', NULL, 3, 'bueno', 2, 3, 3, 3, 8, 'Excelente programa de ejercicios', 'Fisio deportivo', NULL, NOW() - INTERVAL '385 days'),
(2, 3, 'presencial', 'otro', 'Cadenas musculares', 'hombro', NULL, 2, 'normal', 3, 3, 2, 2, 7, 'Trabajo de cadenas muy útil', 'Osteópata', NULL, NOW() - INTERVAL '388 days'),
(3, 3, 'presencial', 'puncion_seca', NULL, 'otra', 'Trapecio', 3, 'bueno', 3, 3, 3, 3, 10, 'Punción seca increíble', 'Médico deportivo', NULL, NOW() - INTERVAL '392 days'),
(2, 1, 'presencial', 'electrolisis', NULL, 'columna_dorsal', NULL, 1, 'malo', 1, 2, 1, 1, 4, 'No recomiendo este centro', 'Folleto publicitario', NULL, NOW() - INTERVAL '395 days'),
(3, 3, 'telematica', 'terapia_manual', NULL, 'columna_lumbar', NULL, 3, 'bueno', 3, 3, 3, 3, 8, 'Muy buena consulta online con ejercicios', 'Seguro médico', NULL, NOW() - INTERVAL '398 days');