-- Insert sample survey responses for testing
INSERT INTO survey_responses (
  website_design_rating,
  treatment_type,
  doctor_listening,
  explanation_clarity,
  consultation_time,
  nps_score,
  how_did_you_know_us,
  waiting_time,
  referral_details,
  appointment_type,
  communication_clarity,
  reception_friendliness,
  clinic_environment,
  body_area,
  other_treatment,
  additional_comments,
  other_body_area,
  created_at
) VALUES 
-- Batch 1 (30 responses)
(9, 'Toxina Botulínica', 10, 9, 8, 9, 'Recomendación', '5-10 minutos', NULL, 'Presencial', 9, 10, 9, 'Rostro', NULL, 'Excelente atención, muy profesional', NULL, NOW() - INTERVAL '45 days'),
(8, 'Rellenos Dérmicos', 9, 8, 7, 8, 'Redes sociales', '10-15 minutos', NULL, 'Presencial', 8, 9, 8, 'Labios', NULL, 'Muy satisfecha con los resultados', NULL, NOW() - INTERVAL '44 days'),
(7, 'Peeling Químico', 8, 7, 6, 7, 'Google', '15-20 minutos', NULL, 'Presencial', 7, 8, 7, 'Rostro', NULL, 'Buen servicio en general', NULL, NOW() - INTERVAL '43 days'),
(10, 'Láser', 10, 10, 9, 10, 'Recomendación', '5-10 minutos', 'Dr. González me recomendó', 'Presencial', 10, 10, 10, 'Piernas', NULL, 'Increíble experiencia, superó mis expectativas', NULL, NOW() - INTERVAL '42 days'),
(6, 'Mesoterapia', 7, 6, 5, 6, 'Publicidad', '20-30 minutos', NULL, 'Presencial', 6, 7, 6, 'Abdomen', NULL, 'El tratamiento fue efectivo pero la espera fue larga', NULL, NOW() - INTERVAL '41 days'),
(9, 'Radiofrecuencia', 9, 8, 8, 9, 'Recomendación', '10-15 minutos', NULL, 'Presencial', 8, 9, 9, 'Rostro', NULL, 'Excelente profesionalismo del equipo', NULL, NOW() - INTERVAL '40 days'),
(8, 'Toxina Botulínica', 8, 9, 7, 8, 'Redes sociales', '5-10 minutos', NULL, 'Presencial', 9, 8, 8, 'Frente', NULL, 'Muy contenta con el resultado natural', NULL, NOW() - INTERVAL '39 days'),
(5, 'Otro', 6, 5, 4, 5, 'Google', '30+ minutos', NULL, 'Presencial', 5, 6, 5, 'Otro', 'Crioterapia', 'La espera fue muy larga y el servicio regular', 'Espalda', NOW() - INTERVAL '38 days'),
(10, 'Rellenos Dérmicos', 10, 10, 9, 10, 'Recomendación', '5-10 minutos', 'Mi hermana me recomendó', 'Presencial', 10, 10, 10, 'Pómulos', NULL, 'Perfecto! No puedo estar más feliz', NULL, NOW() - INTERVAL '37 days'),
(7, 'Peeling Químico', 8, 7, 6, 7, 'Redes sociales', '15-20 minutos', NULL, 'Presencial', 7, 8, 7, 'Rostro', NULL, 'Buenos resultados, recomendaría', NULL, NOW() - INTERVAL '36 days'),
(9, 'Láser', 9, 9, 8, 9, 'Google', '10-15 minutos', NULL, 'Presencial', 9, 9, 9, 'Axilas', NULL, 'Muy efectivo y rápido', NULL, NOW() - INTERVAL '35 days'),
(8, 'Mesoterapia', 8, 8, 7, 8, 'Recomendación', '10-15 minutos', NULL, 'Presencial', 8, 8, 8, 'Rostro', NULL, 'Buena experiencia general', NULL, NOW() - INTERVAL '34 days'),
(6, 'Radiofrecuencia', 7, 6, 6, 6, 'Publicidad', '20-30 minutos', NULL, 'Presencial', 6, 7, 6, 'Abdomen', NULL, 'Servicio aceptable pero mejorable', NULL, NOW() - INTERVAL '33 days'),
(10, 'Toxina Botulínica', 10, 10, 10, 10, 'Recomendación', '5-10 minutos', 'Dr. Martínez', 'Presencial', 10, 10, 10, 'Rostro', NULL, 'Perfecta experiencia en todos los aspectos', NULL, NOW() - INTERVAL '32 days'),
(8, 'Rellenos Dérmicos', 9, 8, 7, 8, 'Redes sociales', '10-15 minutos', NULL, 'Presencial', 8, 9, 8, 'Labios', NULL, 'Muy natural el resultado', NULL, NOW() - INTERVAL '31 days'),
(7, 'Peeling Químico', 7, 7, 6, 7, 'Google', '15-20 minutos', NULL, 'Presencial', 7, 7, 7, 'Rostro', NULL, 'Satisfecha con el tratamiento', NULL, NOW() - INTERVAL '30 days'),
(9, 'Láser', 9, 9, 8, 9, 'Recomendación', '5-10 minutos', NULL, 'Presencial', 9, 9, 9, 'Piernas', NULL, 'Excelente tecnología y atención', NULL, NOW() - INTERVAL '29 days'),
(5, 'Mesoterapia', 6, 5, 4, 5, 'Publicidad', '30+ minutos', NULL, 'Presencial', 5, 6, 5, 'Glúteos', NULL, 'Demasiada espera, servicio regular', NULL, NOW() - INTERVAL '28 days'),
(8, 'Radiofrecuencia', 8, 8, 7, 8, 'Redes sociales', '10-15 minutos', NULL, 'Presencial', 8, 8, 8, 'Rostro', NULL, 'Buenos resultados y atención', NULL, NOW() - INTERVAL '27 days'),
(10, 'Toxina Botulínica', 10, 10, 9, 10, 'Recomendación', '5-10 minutos', 'Amiga del trabajo', 'Presencial', 10, 10, 10, 'Entrecejo', NULL, 'Increíble profesionalismo y resultados', NULL, NOW() - INTERVAL '26 days'),
(6, 'Otro', 7, 6, 5, 6, 'Google', '20-30 minutos', NULL, 'Presencial', 6, 7, 6, 'Otro', 'Hidratación facial', 'Servicio correcto pero nada excepcional', 'Cuello', NOW() - INTERVAL '25 days'),
(9, 'Rellenos Dérmicos', 9, 9, 8, 9, 'Recomendación', '10-15 minutos', NULL, 'Presencial', 9, 9, 9, 'Pómulos', NULL, 'Fantástico resultado, muy profesional', NULL, NOW() - INTERVAL '24 days'),
(7, 'Peeling Químico', 8, 7, 6, 7, 'Redes sociales', '15-20 minutos', NULL, 'Presencial', 7, 8, 7, 'Rostro', NULL, 'Buen tratamiento y seguimiento', NULL, NOW() - INTERVAL '23 days'),
(8, 'Láser', 8, 8, 7, 8, 'Google', '10-15 minutos', NULL, 'Presencial', 8, 8, 8, 'Axilas', NULL, 'Muy efectivo, volveré', NULL, NOW() - INTERVAL '22 days'),
(10, 'Mesoterapia', 10, 10, 9, 10, 'Recomendación', '5-10 minutos', 'Dermatóloga', 'Presencial', 10, 10, 10, 'Rostro', NULL, 'Excelente en todos los aspectos', NULL, NOW() - INTERVAL '21 days'),
(4, 'Radiofrecuencia', 5, 4, 3, 4, 'Publicidad', '30+ minutos', NULL, 'Presencial', 4, 5, 4, 'Abdomen', NULL, 'Mucha espera y resultados no tan buenos', NULL, NOW() - INTERVAL '20 days'),
(9, 'Toxina Botulínica', 9, 9, 8, 9, 'Redes sociales', '5-10 minutos', NULL, 'Presencial', 9, 9, 9, 'Rostro', NULL, 'Muy satisfecha, recomendaré', NULL, NOW() - INTERVAL '19 days'),
(8, 'Rellenos Dérmicos', 8, 8, 7, 8, 'Recomendación', '10-15 minutos', NULL, 'Presencial', 8, 8, 8, 'Labios', NULL, 'Resultado muy natural y bonito', NULL, NOW() - INTERVAL '18 days'),
(7, 'Peeling Químico', 7, 7, 6, 7, 'Google', '15-20 minutos', NULL, 'Presencial', 7, 7, 7, 'Rostro', NULL, 'Tratamiento efectivo', NULL, NOW() - INTERVAL '17 days'),
(10, 'Láser', 10, 10, 9, 10, 'Recomendación', '5-10 minutos', 'Ginecóloga', 'Presencial', 10, 10, 10, 'Piernas', NULL, 'Perfecta experiencia, súper recomendado', NULL, NOW() - INTERVAL '16 days'),

-- Batch 2 (30 responses)
(8, 'Mesoterapia', 8, 8, 7, 8, 'Redes sociales', '10-15 minutos', NULL, 'Presencial', 8, 8, 8, 'Abdomen', NULL, 'Muy buen servicio profesional', NULL, NOW() - INTERVAL '15 days'),
(6, 'Radiofrecuencia', 7, 6, 5, 6, 'Publicidad', '20-30 minutos', NULL, 'Presencial', 6, 7, 6, 'Glúteos', NULL, 'Regular, esperaba más', NULL, NOW() - INTERVAL '14 days'),
(9, 'Toxina Botulínica', 9, 9, 8, 9, 'Recomendación', '5-10 minutos', NULL, 'Presencial', 9, 9, 9, 'Frente', NULL, 'Excelente atención y resultados', NULL, NOW() - INTERVAL '13 days'),
(10, 'Rellenos Dérmicos', 10, 10, 9, 10, 'Google', '10-15 minutos', NULL, 'Presencial', 10, 10, 10, 'Pómulos', NULL, 'Increíble transformación, muy feliz', NULL, NOW() - INTERVAL '12 days'),
(7, 'Peeling Químico', 8, 7, 6, 7, 'Redes sociales', '15-20 minutos', NULL, 'Presencial', 7, 8, 7, 'Rostro', NULL, 'Buenos resultados visibles', NULL, NOW() - INTERVAL '11 days'),
(8, 'Láser', 8, 8, 7, 8, 'Recomendación', '10-15 minutos', NULL, 'Presencial', 8, 8, 8, 'Axilas', NULL, 'Muy efectivo el tratamiento', NULL, NOW() - INTERVAL '10 days'),
(5, 'Otro', 6, 5, 4, 5, 'Publicidad', '30+ minutos', NULL, 'Presencial', 5, 6, 5, 'Otro', 'Limpieza facial', 'Servicio lento pero correcto', 'Espalda', NOW() - INTERVAL '9 days'),
(9, 'Mesoterapia', 9, 9, 8, 9, 'Recomendación', '5-10 minutos', 'Nutricionista', 'Presencial', 9, 9, 9, 'Rostro', NULL, 'Fantástica experiencia', NULL, NOW() - INTERVAL '8 days'),
(8, 'Radiofrecuencia', 8, 8, 7, 8, 'Redes sociales', '10-15 minutos', NULL, 'Presencial', 8, 8, 8, 'Abdomen', NULL, 'Muy profesional todo el equipo', NULL, NOW() - INTERVAL '7 days'),
(10, 'Toxina Botulínica', 10, 10, 9, 10, 'Google', '5-10 minutos', NULL, 'Presencial', 10, 10, 10, 'Rostro', NULL, 'Perfecta, superó expectativas', NULL, NOW() - INTERVAL '6 days'),
(6, 'Rellenos Dérmicos', 7, 6, 5, 6, 'Publicidad', '20-30 minutos', NULL, 'Presencial', 6, 7, 6, 'Labios', NULL, 'Aceptable pero mejorable la espera', NULL, NOW() - INTERVAL '5 days'),
(9, 'Peeling Químico', 9, 9, 8, 9, 'Recomendación', '10-15 minutos', NULL, 'Presencial', 9, 9, 9, 'Rostro', NULL, 'Excelente resultado y atención', NULL, NOW() - INTERVAL '4 days'),
(7, 'Láser', 8, 7, 6, 7, 'Redes sociales', '15-20 minutos', NULL, 'Presencial', 7, 8, 7, 'Piernas', NULL, 'Buen servicio en general', NULL, NOW() - INTERVAL '3 days'),
(8, 'Mesoterapia', 8, 8, 7, 8, 'Google', '10-15 minutos', NULL, 'Presencial', 8, 8, 8, 'Glúteos', NULL, 'Muy satisfecha con resultados', NULL, NOW() - INTERVAL '2 days'),
(10, 'Radiofrecuencia', 10, 10, 9, 10, 'Recomendación', '5-10 minutos', 'Esteticista', 'Presencial', 10, 10, 10, 'Rostro', NULL, 'Increíble servicio y resultados', NULL, NOW() - INTERVAL '1 day'),
(4, 'Otro', 5, 4, 3, 4, 'Publicidad', '30+ minutos', NULL, 'Presencial', 4, 5, 4, 'Otro', 'Depilación', 'Muy lenta la atención', 'Brazos', NOW()),
(9, 'Toxina Botulínica', 9, 9, 8, 9, 'Redes sociales', '5-10 minutos', NULL, 'Presencial', 9, 9, 9, 'Entrecejo', NULL, 'Excelente profesionalismo', NULL, NOW()),
(8, 'Rellenos Dérmicos', 8, 8, 7, 8, 'Recomendación', '10-15 minutos', NULL, 'Presencial', 8, 8, 8, 'Pómulos', NULL, 'Muy natural el resultado', NULL, NOW()),
(7, 'Peeling Químico', 7, 7, 6, 7, 'Google', '15-20 minutos', NULL, 'Presencial', 7, 7, 7, 'Rostro', NULL, 'Buen tratamiento facial', NULL, NOW()),
(10, 'Láser', 10, 10, 9, 10, 'Recomendación', '5-10 minutos', 'Médico familiar', 'Presencial', 10, 10, 10, 'Axilas', NULL, 'Perfecta experiencia completa', NULL, NOW()),
(6, 'Mesoterapia', 7, 6, 5, 6, 'Publicidad', '20-30 minutos', NULL, 'Presencial', 6, 7, 6, 'Abdomen', NULL, 'Correcto pero esperaba más rapidez', NULL, NOW()),
(9, 'Radiofrecuencia', 9, 9, 8, 9, 'Redes sociales', '10-15 minutos', NULL, 'Presencial', 9, 9, 9, 'Glúteos', NULL, 'Muy efectivo y profesional', NULL, NOW()),
(8, 'Toxina Botulínica', 8, 8, 7, 8, 'Google', '10-15 minutos', NULL, 'Presencial', 8, 8, 8, 'Rostro', NULL, 'Buen resultado general', NULL, NOW()),
(5, 'Otro', 6, 5, 4, 5, 'Recomendación', '30+ minutos', NULL, 'Presencial', 5, 6, 5, 'Otro', 'Microdermoabrasión', 'Lento pero efectivo', 'Rostro', NOW()),
(10, 'Rellenos Dérmicos', 10, 10, 9, 10, 'Redes sociales', '5-10 minutos', NULL, 'Presencial', 10, 10, 10, 'Labios', NULL, 'Increíble resultado, muy recomendado', NULL, NOW()),
(7, 'Peeling Químico', 8, 7, 6, 7, 'Publicidad', '15-20 minutos', NULL, 'Presencial', 7, 8, 7, 'Rostro', NULL, 'Satisfecha con el servicio', NULL, NOW()),
(9, 'Láser', 9, 9, 8, 9, 'Recomendación', '10-15 minutos', NULL, 'Presencial', 9, 9, 9, 'Piernas', NULL, 'Excelente tecnología', NULL, NOW()),
(8, 'Mesoterapia', 8, 8, 7, 8, 'Google', '10-15 minutos', NULL, 'Presencial', 8, 8, 8, 'Rostro', NULL, 'Muy profesional el equipo', NULL, NOW()),
(6, 'Radiofrecuencia', 7, 6, 5, 6, 'Redes sociales', '20-30 minutos', NULL, 'Presencial', 6, 7, 6, 'Abdomen', NULL, 'Bueno pero con demoras', NULL, NOW()),
(10, 'Toxina Botulínica', 10, 10, 9, 10, 'Recomendación', '5-10 minutos', 'Cirujano plástico', 'Presencial', 10, 10, 10, 'Frente', NULL, 'Perfecta en todos los aspectos', NULL, NOW()),

-- Batch 3 (30 responses)
(8, 'Rellenos Dérmicos', 9, 8, 7, 8, 'Google', '10-15 minutos', NULL, 'Presencial', 8, 9, 8, 'Pómulos', NULL, 'Muy satisfecha con el resultado', NULL, NOW() - INTERVAL '60 days'),
(7, 'Peeling Químico', 7, 7, 6, 7, 'Redes sociales', '15-20 minutos', NULL, 'Presencial', 7, 7, 7, 'Rostro', NULL, 'Buen tratamiento rejuvenecedor', NULL, NOW() - INTERVAL '59 days'),
(9, 'Láser', 9, 9, 8, 9, 'Recomendación', '5-10 minutos', NULL, 'Presencial', 9, 9, 9, 'Axilas', NULL, 'Excelente y muy rápido', NULL, NOW() - INTERVAL '58 days'),
(5, 'Mesoterapia', 6, 5, 4, 5, 'Publicidad', '30+ minutos', NULL, 'Presencial', 5, 6, 5, 'Glúteos', NULL, 'Demasiada espera para el servicio', NULL, NOW() - INTERVAL '57 days'),
(10, 'Radiofrecuencia', 10, 10, 9, 10, 'Recomendación', '5-10 minutos', 'Fisioterapeuta', 'Presencial', 10, 10, 10, 'Rostro', NULL, 'Increíble resultado y atención', NULL, NOW() - INTERVAL '56 days'),
(8, 'Toxina Botulínica', 8, 8, 7, 8, 'Redes sociales', '10-15 minutos', NULL, 'Presencial', 8, 8, 8, 'Entrecejo', NULL, 'Muy natural el efecto', NULL, NOW() - INTERVAL '55 days'),
(6, 'Otro', 7, 6, 5, 6, 'Google', '20-30 minutos', NULL, 'Presencial', 6, 7, 6, 'Otro', 'Hidrafacial', 'Servicio correcto pero lento', 'Cuello', NOW() - INTERVAL '54 days'),
(9, 'Rellenos Dérmicos', 9, 9, 8, 9, 'Recomendación', '10-15 minutos', NULL, 'Presencial', 9, 9, 9, 'Labios', NULL, 'Fantástico resultado natural', NULL, NOW() - INTERVAL '53 days'),
(7, 'Peeling Químico', 8, 7, 6, 7, 'Publicidad', '15-20 minutos', NULL, 'Presencial', 7, 8, 7, 'Rostro', NULL, 'Buenos resultados visibles', NULL, NOW() - INTERVAL '52 days'),
(8, 'Láser', 8, 8, 7, 8, 'Redes sociales', '10-15 minutos', NULL, 'Presencial', 8, 8, 8, 'Piernas', NULL, 'Muy efectivo el tratamiento', NULL, NOW() - INTERVAL '51 days'),
(10, 'Mesoterapia', 10, 10, 9, 10, 'Google', '5-10 minutos', NULL, 'Presencial', 10, 10, 10, 'Rostro', NULL, 'Excelente en todo sentido', NULL, NOW() - INTERVAL '50 days'),
(4, 'Radiofrecuencia', 5, 4, 3, 4, 'Publicidad', '30+ minutos', NULL, 'Presencial', 4, 5, 4, 'Abdomen', NULL, 'Muy lenta la atención y resultados regulares', NULL, NOW() - INTERVAL '49 days'),
(9, 'Toxina Botulínica', 9, 9, 8, 9, 'Recomendación', '5-10 minutos', NULL, 'Presencial', 9, 9, 9, 'Rostro', NULL, 'Muy profesional y efectivo', NULL, NOW() - INTERVAL '48 days'),
(8, 'Rellenos Dérmicos', 8, 8, 7, 8, 'Redes sociales', '10-15 minutos', NULL, 'Presencial', 8, 8, 8, 'Pómulos', NULL, 'Resultado muy bonito', NULL, NOW() - INTERVAL '47 days'),
(7, 'Peeling Químico', 7, 7, 6, 7, 'Google', '15-20 minutos', NULL, 'Presencial', 7, 7, 7, 'Rostro', NULL, 'Tratamiento efectivo', NULL, NOW() - INTERVAL '46 days'),
(10, 'Láser', 10, 10, 9, 10, 'Recomendación', '5-10 minutos', 'Dermatóloga', 'Presencial', 10, 10, 10, 'Axilas', NULL, 'Perfecta experiencia, súper recomendado', NULL, NOW() - INTERVAL '75 days'),
(6, 'Mesoterapia', 7, 6, 5, 6, 'Publicidad', '20-30 minutos', NULL, 'Presencial', 6, 7, 6, 'Abdomen', NULL, 'Regular, esperaba mejor atención', NULL, NOW() - INTERVAL '74 days'),
(9, 'Radiofrecuencia', 9, 9, 8, 9, 'Redes sociales', '10-15 minutos', NULL, 'Presencial', 9, 9, 9, 'Glúteos', NULL, 'Excelente tecnología y trato', NULL, NOW() - INTERVAL '73 days'),
(8, 'Toxina Botulínica', 8, 8, 7, 8, 'Google', '10-15 minutos', NULL, 'Presencial', 8, 8, 8, 'Frente', NULL, 'Buen resultado y atención', NULL, NOW() - INTERVAL '72 days'),
(5, 'Otro', 6, 5, 4, 5, 'Recomendación', '30+ minutos', NULL, 'Presencial', 5, 6, 5, 'Otro', 'Plasma rico en plaquetas', 'Lento pero con buenos resultados', 'Rostro', NOW() - INTERVAL '71 days'),
(10, 'Rellenos Dérmicos', 10, 10, 9, 10, 'Redes sociales', '5-10 minutos', NULL, 'Presencial', 10, 10, 10, 'Labios', NULL, 'Increíble transformación, muy feliz', NULL, NOW() - INTERVAL '70 days'),
(7, 'Peeling Químico', 8, 7, 6, 7, 'Publicidad', '15-20 minutos', NULL, 'Presencial', 7, 8, 7, 'Rostro', NULL, 'Satisfecha con los resultados', NULL, NOW() - INTERVAL '69 days'),
(9, 'Láser', 9, 9, 8, 9, 'Recomendación', '10-15 minutos', NULL, 'Presencial', 9, 9, 9, 'Piernas', NULL, 'Excelente servicio y resultados', NULL, NOW() - INTERVAL '68 days'),
(8, 'Mesoterapia', 8, 8, 7, 8, 'Google', '10-15 minutos', NULL, 'Presencial', 8, 8, 8, 'Rostro', NULL, 'Muy profesional el equipo', NULL, NOW() - INTERVAL '67 days'),
(6, 'Radiofrecuencia', 7, 6, 5, 6, 'Redes sociales', '20-30 minutos', NULL, 'Presencial', 6, 7, 6, 'Abdomen', NULL, 'Correcto pero con demoras', NULL, NOW() - INTERVAL '66 days'),
(10, 'Toxina Botulínica', 10, 10, 9, 10, 'Recomendación', '5-10 minutos', 'Médico estético', 'Presencial', 10, 10, 10, 'Rostro', NULL, 'Perfecta en todos los aspectos', NULL, NOW() - INTERVAL '65 days'),
(8, 'Rellenos Dérmicos', 9, 8, 7, 8, 'Publicidad', '10-15 minutos', NULL, 'Presencial', 8, 9, 8, 'Pómulos', NULL, 'Muy satisfecha con el resultado', NULL, NOW() - INTERVAL '64 days'),
(7, 'Peeling Químico', 7, 7, 6, 7, 'Google', '15-20 minutos', NULL, 'Presencial', 7, 7, 7, 'Rostro', NULL, 'Buen tratamiento facial', NULL, NOW() - INTERVAL '63 days'),
(9, 'Láser', 9, 9, 8, 9, 'Redes sociales', '5-10 minutos', NULL, 'Presencial', 9, 9, 9, 'Axilas', NULL, 'Excelente y muy rápido', NULL, NOW() - INTERVAL '62 days'),
(4, 'Otro', 5, 4, 3, 4, 'Publicidad', '30+ minutos', NULL, 'Presencial', 4, 5, 4, 'Otro', 'Carboxiterapia', 'Mucha espera y atención regular', 'Piernas', NOW() - INTERVAL '61 days'),

-- Batch 4 (30 responses)
(10, 'Mesoterapia', 10, 10, 9, 10, 'Recomendación', '5-10 minutos', 'Nutricionista', 'Presencial', 10, 10, 10, 'Rostro', NULL, 'Increíble servicio y resultados', NULL, NOW() - INTERVAL '90 days'),
(8, 'Radiofrecuencia', 8, 8, 7, 8, 'Redes sociales', '10-15 minutos', NULL, 'Presencial', 8, 8, 8, 'Glúteos', NULL, 'Muy efectivo el tratamiento', NULL, NOW() - INTERVAL '89 days'),
(6, 'Toxina Botulínica', 7, 6, 5, 6, 'Google', '20-30 minutos', NULL, 'Presencial', 6, 7, 6, 'Entrecejo', NULL, 'Bueno pero con esperas largas', NULL, NOW() - INTERVAL '88 days'),
(9, 'Rellenos Dérmicos', 9, 9, 8, 9, 'Publicidad', '10-15 minutos', NULL, 'Presencial', 9, 9, 9, 'Labios', NULL, 'Fantástico resultado natural', NULL, NOW() - INTERVAL '87 days'),
(7, 'Peeling Químico', 8, 7, 6, 7, 'Recomendación', '15-20 minutos', NULL, 'Presencial', 7, 8, 7, 'Rostro', NULL, 'Buenos resultados visibles', NULL, NOW() - INTERVAL '86 days'),
(8, 'Láser', 8, 8, 7, 8, 'Redes sociales', '10-15 minutos', NULL, 'Presencial', 8, 8, 8, 'Piernas', NULL, 'Muy profesional todo', NULL, NOW() - INTERVAL '85 days'),
(5, 'Otro', 6, 5, 4, 5, 'Google', '30+ minutos', NULL, 'Presencial', 5, 6, 5, 'Otro', 'Drenaje linfático', 'Servicio lento pero efectivo', 'Abdomen', NOW() - INTERVAL '84 days'),
(10, 'Mesoterapia', 10, 10, 9, 10, 'Recomendación', '5-10 minutos', 'Esteticista', 'Presencial', 10, 10, 10, 'Abdomen', NULL, 'Excelente en todo sentido', NULL, NOW() - INTERVAL '83 days'),
(8, 'Radiofrecuencia', 8, 8, 7, 8, 'Publicidad', '10-15 minutos', NULL, 'Presencial', 8, 8, 8, 'Rostro', NULL, 'Buen servicio profesional', NULL, NOW() - INTERVAL '82 days'),
(7, 'Toxina Botulínica', 7, 7, 6, 7, 'Redes sociales', '15-20 minutos', NULL, 'Presencial', 7, 7, 7, 'Rostro', NULL, 'Satisfecha con el resultado', NULL, NOW() - INTERVAL '81 days'),
(9, 'Rellenos Dérmicos', 9, 9, 8, 9, 'Google', '5-10 minutos', NULL, 'Presencial', 9, 9, 9, 'Pómulos', NULL, 'Excelente resultado y atención', NULL, NOW() - INTERVAL '80 days'),
(6, 'Peeling Químico', 7, 6, 5, 6, 'Recomendación', '20-30 minutos', NULL, 'Presencial', 6, 7, 6, 'Rostro', NULL, 'Regular, esperaba más rapidez', NULL, NOW() - INTERVAL '79 days'),
(8, 'Láser', 8, 8, 7, 8, 'Publicidad', '10-15 minutos', NULL, 'Presencial', 8, 8, 8, 'Axilas', NULL, 'Muy efectivo y rápido', NULL, NOW() - INTERVAL '78 days'),
(10, 'Mesoterapia', 10, 10, 9, 10, 'Redes sociales', '5-10 minutos', NULL, 'Presencial', 10, 10, 10, 'Glúteos', NULL, 'Perfecta experiencia completa', NULL, NOW() - INTERVAL '77 days'),
(4, 'Otro', 5, 4, 3, 4, 'Google', '30+ minutos', NULL, 'Presencial', 4, 5, 4, 'Otro', 'Ultrasonido', 'Muy lenta la atención', 'Abdomen', NOW() - INTERVAL '76 days'),
(9, 'Radiofrecuencia', 9, 9, 8, 9, 'Recomendación', '10-15 minutos', NULL, 'Presencial', 9, 9, 9, 'Rostro', NULL, 'Excelente tecnología', NULL, NOW() - INTERVAL '105 days'),
(8, 'Toxina Botulínica', 8, 8, 7, 8, 'Redes sociales', '10-15 minutos', NULL, 'Presencial', 8, 8, 8, 'Frente', NULL, 'Muy natural el resultado', NULL, NOW() - INTERVAL '104 days'),
(7, 'Rellenos Dérmicos', 8, 7, 6, 7, 'Publicidad', '15-20 minutos', NULL, 'Presencial', 7, 8, 7, 'Labios', NULL, 'Buen resultado general', NULL, NOW() - INTERVAL '103 days'),
(10, 'Peeling Químico', 10, 10, 9, 10, 'Google', '5-10 minutos', NULL, 'Presencial', 10, 10, 10, 'Rostro', NULL, 'Increíble transformación', NULL, NOW() - INTERVAL '102 days'),
(6, 'Láser', 7, 6, 5, 6, 'Recomendación', '20-30 minutos', NULL, 'Presencial', 6, 7, 6, 'Piernas', NULL, 'Correcto pero con demoras', NULL, NOW() - INTERVAL '101 days'),
(9, 'Mesoterapia', 9, 9, 8, 9, 'Redes sociales', '10-15 minutos', NULL, 'Presencial', 9, 9, 9, 'Rostro', NULL, 'Muy satisfecha con todo', NULL, NOW() - INTERVAL '100 days'),
(8, 'Radiofrecuencia', 8, 8, 7, 8, 'Publicidad', '10-15 minutos', NULL, 'Presencial', 8, 8, 8, 'Abdomen', NULL, 'Profesional y efectivo', NULL, NOW() - INTERVAL '99 days'),
(5, 'Otro', 6, 5, 4, 5, 'Google', '30+ minutos', NULL, 'Presencial', 5, 6, 5, 'Otro', 'Radiofrecuencia facial', 'Lento pero con resultados', 'Cuello', NOW() - INTERVAL '98 days'),
(10, 'Toxina Botulínica', 10, 10, 9, 10, 'Recomendación', '5-10 minutos', 'Dermatóloga', 'Presencial', 10, 10, 10, 'Rostro', NULL, 'Perfecta en todos los aspectos', NULL, NOW() - INTERVAL '97 days'),
(7, 'Rellenos Dérmicos', 7, 7, 6, 7, 'Redes sociales', '15-20 minutos', NULL, 'Presencial', 7, 7, 7, 'Pómulos', NULL, 'Tratamiento efectivo', NULL, NOW() - INTERVAL '96 days'),
(8, 'Peeling Químico', 8, 8, 7, 8, 'Publicidad', '10-15 minutos', NULL, 'Presencial', 8, 8, 8, 'Rostro', NULL, 'Muy buen servicio', NULL, NOW() - INTERVAL '95 days'),
(9, 'Láser', 9, 9, 8, 9, 'Google', '5-10 minutos', NULL, 'Presencial', 9, 9, 9, 'Axilas', NULL, 'Excelente y rápido', NULL, NOW() - INTERVAL '94 days'),
(6, 'Mesoterapia', 7, 6, 5, 6, 'Recomendación', '20-30 minutos', NULL, 'Presencial', 6, 7, 6, 'Glúteos', NULL, 'Bueno pero mejorable', NULL, NOW() - INTERVAL '93 days'),
(10, 'Radiofrecuencia', 10, 10, 9, 10, 'Redes sociales', '5-10 minutos', NULL, 'Presencial', 10, 10, 10, 'Rostro', NULL, 'Increíble resultado', NULL, NOW() - INTERVAL '92 days'),
(8, 'Toxina Botulínica', 8, 8, 7, 8, 'Publicidad', '10-15 minutos', NULL, 'Presencial', 8, 8, 8, 'Entrecejo', NULL, 'Muy satisfecha', NULL, NOW() - INTERVAL '91 days');