// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqzcchiglzggyamwxlqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtxemNjaGlnbHpnZ3lhbXd4bHFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwODU3ODQsImV4cCI6MjA3MjY2MTc4NH0.yD__EIhICVxTQIhAKXsynmzc_wF9ITt4zum_7a-CpAg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});